### ISSUE TITLE
Plans on making this work with Matrix fields?

### ISSUE THREAD

**Issue by superwick** [timkelty/craft-localesync#1]
Plugin seems to work fine with fields that aren't in Matrix blocks. I'm hoping to see a solution that work in Matrix. I understand Matrix is a complicated beast though. ;-)

**Comment by timkelty** [comment]
I haven't dug into that yet, but would like to.
We will likely need that for the project I made this for, so I'll probably have to take a look in the coming weeks.

Until then - PRs welcome!

**Comment by erktime** [comment]
I had a need to see this working for matrix fields, and i dug in and found things to work with a small code change: https://github.com/timkelty/craft-localesync/pull/6

**Comment by superwick** [comment]
I can't believe it was that easy!

**Comment by timkelty** [comment]
Nice work @erktime! I'll try and review shortly and get it merged in.

**Comment by timkelty** [comment]
Included in 1.3 release. Thanks @erktime!
