### ISSUE TITLE
Overwrite from the entry HUD

### ISSUE THREAD

**Issue by oyvindostmo** [timkelty/craft-localesync#11]
Hi,
it says in the readme that overwrite from the entry HUD doesn't work. That's the one functionality I was after so be able to "reset" locale versions for a specific entry, whenever the entry is ready for translation. Any ETA on when that could be working again?

**Comment by timkelty** [comment]
I don't have any current plans for this, only because the necessary hooks don't exist.
Note that syncing will still work using your default settings, there is just no where to control the overrides for that entry.

**Comment by timkelty** [comment]
This should be possible w/ a Craft 3 port, so it likely wont happen until then.

**Comment by timkelty** [comment]
Craft 3 version is now implemented as a field, so it will work in the HUD
