### ISSUE TITLE
updating about Matrix field

### ISSUE THREAD

**Issue by didoweb** [timkelty/craft-localesync#16]
Hi, sorry if I've open a new issue
but I wanna know if the plugin works with Matrix field on Craft v. 2.6+
because I've installed it but it doesn't sync this kind of field.

Thanks in advance and regards,

Davide

**Comment by timkelty** [comment]
Is the matrix field marked as translatable? 

There are some gotchas with Matrix fields, please see discussion here: https://github.com/timkelty/craft-localesync/issues/10
