### ISSUE TITLE
Can't manage to install the plugin

### ISSUE THREAD

**Issue by frontedbe** [timkelty/craft-localesync#17]
Hi there,

I keep bumping into install issues when I do:
_$ composer require timkelty/craft-localesync_
I get this error => [screenshot](https://cl.ly/6ca2deb30aab)

Running the latest Craft 3.0.34. 

Thanks in advance!

**Comment by timkelty** [comment]
@mdominguez for Craft 3 it should be:
```
composer require timkelty/craft-site-sync
```

I apologize for the lack of docs, Its on my list!

**Comment by frontedbe** [comment]
@timkelty Thanks! Unfortunately doesn't seem to work either.. => [screenshot](https://cl.ly/431d35ca5fdf)

**Comment by timkelty** [comment]
ah ya know what, I never even released it to packagist, so that wont work either…let me do that quickly…

**Comment by timkelty** [comment]
@mdominguez Ok, you should be able to now!
```
composer require timkelty/craft-site-sync:1.0.*@dev
```

I plan on working on docs in the next week.

**Comment by frontedbe** [comment]
Ok thanks! Just installed the plugin and don't see anything happening when saving entries, maybe because I don't know how this plugin works? I can't seem to find anything related to it in the CP..

**Comment by timkelty** [comment]
@mdominguez you need to add a Site-sync setting field to whatever field layout you'd like to perform the syncing on.
