### ISSUE TITLE
Selecting which sites to sync

### ISSUE THREAD

**Issue by billymedia** [timkelty/craft-localesync#23]
Am i missing something, in the craft 2 version, you could select which locales to sync, whereas with the craft 3 version, as far as i can see, it syncs with all sites regardless, is that correct?

i have a scenario where i want to sync an entry only with one other site out of the 4 i have setup, is that possible? i need to be able to select which sites to sync.

**Comment by timkelty** [comment]
@billymedia currently, content will sync with any sites _that the current user has permission for_, but there is no site-selection like in the Craft 2 version.

It is planned though, I just haven't had the need for it yet: https://github.com/timkelty/craftcms-site-sync/issues/19

You're the second person to ask, so I'll see if I can squeeze it in soon.

FWIW, you could approximate this by using different users, with different permissions. So when you want to sync 1/4 sites, log in as a user that only has permissions to the 2 sites (source and where you are syncing to). I know that's not what you want, but thought I'd mention it.

Follow along here: https://github.com/timkelty/craftcms-site-sync/issues/19
