### ISSUE TITLE
Invalid path alias: @timkelty/craft/sitesync/resources/web

### ISSUE THREAD

**Issue by engram-design** [timkelty/craft-localesync#24]
As per https://github.com/timkelty/craftcms-site-sync/issues/21 this is still an issue. 

Change in `FieldAssets.php` from:
`$this->sourcePath = "@timkelty/craft/sitesync/resources/web";`
to
`$this->sourcePath = "@timkelty/craftcms/sitesync/resources/web";`

**Comment by timkelty** [comment]
Thanks @engram-design.

I'll get back to this this week and make sure things are working with 3.2 as well.

**Comment by timkelty** [comment]
@engram-design wait a minute…that _is_ fixed: https://github.com/timkelty/craftcms-site-sync/blob/1.0.3/src/FieldAssets.php#L11

Can you make sure you're on the latest 1.0.3?

**Comment by engram-design** [comment]
Whoops, you're right, because I forgot to update composer.json to:
```
"platform": {
    "php": "7.1"
 }
```

Sorry for the false alarm!
