### ISSUE TITLE
Craft 3.4 Compatibility?

### ISSUE THREAD

**Issue by michaelfromtheoutfit** [timkelty/craft-localesync#26]
Hey Tim!

I'm wondering if I'm just doing something wrong, or if this plugin no longer works with the newer versions of Craft.

I've: 

- installed the plugin
- added my settings field to my Section field layout
- Enabled the field with "All Content" selected as well as Overwrite enabled

But no matter what I do, the changes don't seem to propagate over to my other sites/languages.

Before I kept looking into this I was just wondering if you can confirm that the plugin works with 3.4. Thanks so much!

**Comment by timkelty** [comment]
Yes – I can confirm it works on 3.4.24.

**Comment by timkelty** [comment]
@michaelfromtheoutfit is the translation method for the fields you're trying to use it with set to "Translate for each site"?

**Comment by michaelfromtheoutfit** [comment]
Hey @timkelty, it is! Super weird. I'll dig into it a little bit and see if I can figure out what is going on. No need to keep this item open, I'll update it if I am able to resolve what the issue was.

Thanks for the plugin!

MW

**Comment by timkelty** [comment]
Hmmm - otherwise if you can get me your composer.json/lock files and a database dump, I'm happy to take a look.
