### ISSUE TITLE
Implement as a fieldtype

### ISSUE THREAD

**Issue by timkelty** [timkelty/craft-localesync#3]
This would give us per-entry persisting settings (not sure if that's desirable though...), and would also allow it to work in the HUD.

**Comment by balazscsaba2006** [comment]
+1 for the implementation using a fieldtype, that will allow it to work in the HUD.

**Comment by timkelty** [comment]
This is done in the Craft 3 version: https://github.com/timkelty/craft-site-sync/tree/2.0.0
