### ISSUE TITLE
Does this work with titles for assets?

### ISSUE THREAD

**Issue by juskaiser** [timkelty/craft-localesync#4]
I'd like something similar that could synchronize asset titles across locales. However, it looks like this plugin only works with entires at the moment. Feature request to allow syncing of asset fields (titles) across locales.

**Comment by timkelty** [comment]
@juskaiser It _should_ work for all elements (uses the `elements.onBeforeSaveElement` event). If it isn't working in this case I bet it is something specific with assets. I'll take a look.

**Comment by timkelty** [comment]
@juskaiser Grab the latest version `1.5.0`.

Any element types, as well as their matching field types should now work.
